---
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: quay.io/kurama/jwc-frontend
    newName: quay.io/kurama/jwc-frontend
    newTag: main

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
